version: 1.0

settings:
  message:
    radius: 10.4 # in blocks
    format-thrower: "You throw dice {roll}" #placeholders and {dice_name}, {dice_title}, {roll}, {roll_probability}, {thrower_name}
    format-seer: "Player {thrower_name} throw dice {roll}" #placeholders and {dice_name}, {dice_title}, {roll}, {roll_probability}, {thrower_name}, {seer_name}

dices:
  test-d-4:
    name: "Четырёхгранник"
    sides: [1,2,3,4]
  test-d-6:
    name: "Шестигранник"
    sides: [ 1,2,3,4,5,6 ]
  test-d-8:
    name: "Восьмигранник"
    sides: [ 1,2,3,4,5,6,7,8 ]
  test-d-10:
    name: "Десятигранник"
    sides: [1,2,3,4,5,6,7,8,9,10]
  test-d-12:
    name: "Двенадцатигранник"
    sides: [1,2,3,4,5,6,7,8,9,10,11,12]
  test-d-12-prob-weight:
    name: "Модифицированный Двенадцатигранник"
    sides: [1,2,3,4,5,6,7,8,9,10,11,12]
    prob-weight:
      "1": 5
      "2": 6
      "11": 0.8
      "12": 0.8
  test-d-TF:
    name: "Состояние"
    side: ["&aУспех", "&cПровал"]
  test-d-D:
    name: "Судьба"
    side: ["☠","💖","💥","💨","🦴","✔","⭕"]
    prob-weight:
      "☠": 2
      "🦴": 2
      "🟩": 0.5

